name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: swift test
      run: |
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" \
        swift test
