name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Swift
      run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    - name: swift test
      run: swift test
